"""initial_tables

Revision ID: b6557d668923
Revises: 
Create Date: 2026-09-17 19:42:17.691010+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
import app.database

# revision identifiers, used by Alembic.
revision: str = 'b6557d668923'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_rates',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('cargo_type', sa.String(length=64), nullable=False),
    sa.Column('rate_usd_per_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_rates_cargo_type'), 'freight_rates', ['cargo_type'], unique=False)
    op.create_index(op.f('ix_freight_rates_date'), 'freight_rates', ['date'], unique=False)
    op.create_index(op.f('ix_freight_rates_destination'), 'freight_rates', ['destination'], unique=False)
    op.create_index(op.f('ix_freight_rates_id'), 'freight_rates', ['id'], unique=False)
    op.create_index(op.f('ix_freight_rates_origin'), 'freight_rates', ['origin'], unique=False)
    op.create_index(op.f('ix_freight_rates_route'), 'freight_rates', ['route'], unique=False)
    op.create_table('port_snapshots',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('port_id', sa.String(length=64), nullable=False),
    sa.Column('congestion_level', sa.String(length=32), nullable=False),
    sa.Column('berthing_wait_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('handling_rate_mt_per_day', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weather_risk', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_snapshots_id'), 'port_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_port_snapshots_port_id'), 'port_snapshots', ['port_id'], unique=False)
    op.create_index(op.f('ix_port_snapshots_recorded_at'), 'port_snapshots', ['recorded_at'], unique=False)
    op.create_table('users',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', app.database.UniversalUUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('impact_metric', sa.String(length=128), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('cargo_requests',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', app.database.UniversalUUID(), nullable=False),
    sa.Column('cargo_type', sa.String(length=64), nullable=False),
    sa.Column('cargo_quantity_mt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('origin_country', sa.String(length=128), nullable=False),
    sa.Column('destination_port', sa.String(length=128), nullable=False),
    sa.Column('required_delivery_date', sa.Date(), nullable=True),
    sa.Column('loading_window_start', sa.Date(), nullable=True),
    sa.Column('loading_window_end', sa.Date(), nullable=True),
    sa.Column('discharge_window_start', sa.Date(), nullable=True),
    sa.Column('discharge_window_end', sa.Date(), nullable=True),
    sa.Column('preferred_vessel_type', sa.String(length=64), nullable=True),
    sa.Column('max_acceptable_freight', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('number_of_voyages', sa.Integer(), nullable=False),
    sa.Column('contract_duration', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_requests_id'), 'cargo_requests', ['id'], unique=False)
    op.create_index(op.f('ix_cargo_requests_user_id'), 'cargo_requests', ['user_id'], unique=False)
    op.create_table('voyage_plans',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('cargo_request_id', app.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', app.database.UniversalUUID(), nullable=False),
    sa.Column('recommended_vessel_class', sa.String(length=64), nullable=False),
    sa.Column('final_vessel_class', sa.String(length=64), nullable=False),
    sa.Column('vessel_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('freight_cost_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('port_charges_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loading_discharge_cost_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('idle_waiting_cost_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('demurrage_exposure_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost_inr', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_per_mt_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_rate_per_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_idle_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('risk_score_overall', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_bucket', sa.String(length=32), nullable=False),
    sa.Column('simulator_overrides', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_request_id'], ['cargo_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voyage_plans_cargo_request_id'), 'voyage_plans', ['cargo_request_id'], unique=False)
    op.create_index(op.f('ix_voyage_plans_id'), 'voyage_plans', ['id'], unique=False)
    op.create_index(op.f('ix_voyage_plans_user_id'), 'voyage_plans', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', app.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', app.database.UniversalUUID(), nullable=False),
    sa.Column('voyage_plan_id', app.database.UniversalUUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voyage_plan_id'], ['voyage_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_reports_voyage_plan_id'), 'reports', ['voyage_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_voyage_plan_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_voyage_plans_user_id'), table_name='voyage_plans')
    op.drop_index(op.f('ix_voyage_plans_id'), table_name='voyage_plans')
    op.drop_index(op.f('ix_voyage_plans_cargo_request_id'), table_name='voyage_plans')
    op.drop_table('voyage_plans')
    op.drop_index(op.f('ix_cargo_requests_user_id'), table_name='cargo_requests')
    op.drop_index(op.f('ix_cargo_requests_id'), table_name='cargo_requests')
    op.drop_table('cargo_requests')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_port_snapshots_recorded_at'), table_name='port_snapshots')
    op.drop_index(op.f('ix_port_snapshots_port_id'), table_name='port_snapshots')
    op.drop_index(op.f('ix_port_snapshots_id'), table_name='port_snapshots')
    op.drop_table('port_snapshots')
    op.drop_index(op.f('ix_freight_rates_route'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_origin'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_id'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_destination'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_date'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_cargo_type'), table_name='freight_rates')
    op.drop_table('freight_rates')
    # ### end Alembic commands ###
